#!/bin/bash

## Files and cmd
FILE="$HOME/.cache/eww_launch.xyz"

# Run the hyprctl command and pipe the output to grep
# Use grep to match lines that start with 'Monitor' and extract the monitor names
monitor_list=$(hyprctl monitors all | grep -oP '^Monitor \K.*(?= \(ID)')

# Convert the monitor names into a bash array
monitor_array=($monitor_list)

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
    eww daemon
    sleep 1
fi

## Open widgets 
screen_counter=0
for monitor in "${monitor_array[@]}"
do
  echo "$monitor"
  eww open-many bar:bar_$monitor \
    --arg bar_$monitor:screen=$screen_counter


  screen_counter=$((screen_counter+1))
done

# Run the main loop of wifi status listener
bun run $HOME/.config/eww/scripts/wifi/index.ts main
