# Cursor
#
# Default cursor is Block
# Other available options are: '_' and '|'
# cursor = '_'

# Blinking Cursor
#
# Default is false
#
# blinking_cursor = true


# Theme
#
# It makes Rio look for the specified theme in the themes folder
# (macos and linux: ~/.config/rio/themes/dracula.toml)
# (windows: C:\Users\USER\AppData\Local\rio\themes\dracula.toml)
#
# Dracula theme code is available in:
# https://github.com/dracula/rio-terminal
#
theme = "gruvbox"

# Padding-x
#
# define x axis padding (default is 10)
#
padding-x = 0

[renderer]
# Performance
#
# Set WGPU rendering performance
# High: Adapter that has the highest performance. This is often a discrete GPU.
# Low: Adapter that uses the least possible power. This is often an integrated GPU.
#
performance = "Low"
# backend = "Vulkan"

[window]
foreground-opacity = 1.0
background-opacity = 0.75
blur = true


# Fonts
#
# Configure fonts used by the terminal
#
# Note: You can set different font families but Rio terminal
# will always look for regular font bounds whene
#
# Another Note: "cascadiamono" font is built-in.
#
[fonts]
size = 16

# # You can also set family on root to overwritte all fonts
family = "Fira Code"

# [fonts.regular]
# family = "Fira Code"
# style = "normal"
# weight = 400
# 
# [fonts.bold]
# family = "Fira Code"
# style = "normal"
# weight = 800
# 
# [fonts.italic]
# family = "Fira Code"
# style = "italic"
# weight = 400
# 
# [fonts.bold-italic]
# family = "Fira Code"
# style = "italic"
# weight = 800

# Navigation
#
# "mode" - Define navigation mode
#   - NativeTab (MacOs only)
#   - CollapsedTab
#   - BottomTab
#   - TopTab
#   - Breadcrumb
#
# "clickable" - Enable click on tabs to switch.
# "use-current-path" - Use same path whenever a new tab is created.
# "color-automation" - Set a specific color for the tab whenever a specific program is running.
# "macos-hide-window-buttons" - (MacOS only) Hide window buttons
#
# [navigation]
# mode = "BottomTab"
# clickable = false
# use-current-path = true
# color-automation = [
#   { program = "nvim", color = "#FFFF00" }
# ]
# macos-hide-window-buttons = false

# Disable render when unfocused
#
# This property disable renderer processes while Rio is unfocused.
#
# disable-renderer-when-unfocused = false

# Use fork
#
# Defaults for POSIX-based systems (Windows is not configurable):
# MacOS: spawn processes
# Linux/BSD: fork processes
#
# use-fork = false

# Colors
#
# Colors definition will overwrite any property in theme
# (considering if theme folder does exists and is being used)
#
# [colors]
# background = "#BBBD64"
# foreground = "#040400"
# cursor = "#242805"
# tabs-active = "#F8A145"
# blue = "#454A12"


# Bindings
#
# Create custom Key bindings for Rio terminal
# More information in: raphamorim.io/rio/docs/custom-key-bindings
#
[bindings]
keys = [
  { key = "space", with = "control | shift", action = "ToggleVIMode" }
]

# [developer]
# Log level
#
# This property enables log level filter. Default is "OFF".
#
# log-level = "INFO"
