
# Terminal emulator
super + Return
  alacritty

super + shift + Return
  alacritty --class float

super + e
  thunar

# Clipboard manager
super + v
  copyq toggle

super + space
  alacritty --class float -o "font.size=18" --command julia --banner no &

# program launcher
alt + { _; super} + space
  rofi -show {drun; run} -dpi 150 -show-icons

# Screenshot and copy to Clipboard
super + alt + 5
  slurp | grim -g - - | wl-copy && \
  notify-send --icon photo "Screenshot copied" &

# screen recording
super + alt + 6
  kooha

# toggle enable/disable trackpad while typing on keyboard
super + alt + 0
  hypr: toggle_trackpad_while_typing()

# show power menu when power button is pressed
# add `HandlePowerKey=ignore` to `/etc/systemd/logind.conf`
XF86PowerOff
  ../eww/scripts/toggle_powermenu.sh

# Brightness
( locked, repeating )
XF86MonBrightness{Down;Up}
  swayosd-client --brightness={lower; raise}

# Volume
( locked, repeating )
XF86Audio{Lower;Raise}Volume
  swayosd-client --output-volume={-;+}2

( locked )
XF86AudioMute
  swayosd-client --output-volume=mute-toggle

# Audio control
( locked )
XF86AudioPlay
  ./scripts/playerctl.sh play-pause

( locked )
super + XF86AudioPlay
  ./scripts/playerctl.sh shuffle

# F4 = fn + XF86AudioPlay
( locked )
super + alt + F4
  ./scripts/playerctl.sh toggle-loop

( locked )
super + XF86Audio{Lower;Raise}Volume
  ./scripts/playerctl.sh position 5{-; +}
 
( locked )
super + alt + XF86Audio{Lower;Raise}Volume
  ./scripts/playerctl.sh {previous; next}



# test
( locked )
super + p
  swayosd-client --custom-message="type shit"

#
# hyprland hotkeys
#

# quit/restart hyprland
super + alt + {q;r}
  hypr: {exit(); reload()}



# super + g
#   hypr: hy3:makegroup tab, ephemeral
super + g
  hypr: group.toggle()
#
# super + w
#   hypr: hy3:killactive
super + w
  hypr: window.close()

# alternate between the tiled and monocle layout
super + m
  hypr: window.fullscreen(2)

# super + {_, alt} + t
#   hypr: hy3:changegroup {opposite, toggletab}



#
# state/flags
#

# set the window state
#super + {t,shift + t,s,f}
super + f
  hypr: window.float(action="toggle")


#
# focus/swap
#

# focus the node in the given direction
# super + {_, alt} + {h,j,k,l}
#   hypr: {focus, hy3:focustab} {l,d,u,r}
super + {h; j; k; l}
  hypr: focus(direction={left;down;up;right})

super + alt + {h; l}
  hypr: group.{prev; next}()

# move window in the given direction
( repeating )
super + shift + {h;j;k;l}
  hypr: move_win(direction={left;down;up;right})

super + alt + shift + {h; l}
  hypr: move_win_in_out_group(direction={left; right})
 

# focus/move-window-to the next/previous desktop in the current monitor

alt + {_; shift} + bracket{left; right}
  hypr: {focus; window.move}(workspace="r{-;+}1")

super + {_; shift} + {1-9;0}
  hypr: {focus; window.move}(workspace={1-9;10})



#
# move/resize
#

# resize windows
( repeating )
super + ctrl + {h; j; k; l}
  hypr: window.resize({x=-20, y=0; x=0, y=20; x=0, y=-20; x=20, y=0}, relative=true)

( mouse )
super + {_; shift} + mouse:272
  hypr: {window.drag(); window.resize()}


( non_consuming )
super + super_l
  eww update meta_pressed=true

( non_consuming, release )
super + super_l
  eww update meta_pressed=false
