[font]
size = 9.5

[font.normal]
family = "FiraCode Nerd Font"

[window]
opacity = 0.7
blur = true

[window.dimensions]
columns = 90
lines = 30

[cursor]
vi_mode_style = { blinking = "On" }
blink_interval = 300
